const $=s=>document.querySelector(s);let screens=[],current='dashboard',timer=null,walkIndex=0,phoneIndex=0,lastFocus=false,paired=false,temperature=21,resumeScreen='dashboard',privacyOrigin='dashboard';const walk=['dashboard','welcome','overview','seat','controls','wipers','phone','pair','connected','reviewconnected','homeconnected'];const reduced=matchMedia('(prefers-reduced-motion: reduce)');
function stop(){clearInterval(timer);timer=null;$('#play').textContent='Play walkthrough ▷';$('#play').setAttribute('aria-pressed','false')}
function show(id,manual=true){
 if(id==='locked'&&current!=='locked')resumeScreen=current;
 if(id==='privacy'&&current!=='privacy')privacyOrigin=current;
 if(id==='connected')paired=true;if(id==='pairerror')paired=false;
 if(id==='cleared'){paired=false;temperature=21;resumeScreen='welcome';privacyOrigin='dashboard'}
 if(id==='climate20')temperature=20;if(id==='climate22')temperature=22;
 if(id==='climate')id=temperature===21?'climate':'climate'+temperature;
 if(id==='review'&&paired)id='reviewconnected';if(id==='home'&&paired)id='homeconnected';
 const s=screens.find(x=>x.id===id);if(!s)return;if(manual)stop();current=id;const box=$('#hmi');const focused=box.contains(document.activeElement);box.replaceChildren();const img=document.createElement('img');img.src=`screens/${id==='welcome'?'welcome-premium':id==='dashboard'?'dashboard-'+temperature+'-'+(paired?'connected':'unconnected'):id}.svg`;img.alt=s.title.replaceAll('\n',' ')+'. '+s.sub;img.className='changing';box.append(img);for(const e of s.elements.filter(x=>x.to)){if(id==='welcome'&&e.to==='welcome')continue;if(id==='locked'&&e.label==='Back')continue;const button=document.createElement('button');const label=id==='dashboard'&&e.to==='phone'&&paired?'Manage connection':e.label;button.setAttribute('aria-label',label);button.textContent=label;Object.assign(button.style,{left:e.x/12.8+'%',top:e.y/8+'%',width:e.w/12.8+'%',height:e.h/8+'%'});button.onclick=()=>{
 if(e.label==='Disconnect phone')paired=false;
 if(e.label==='21°C'){temperature=21;show('climate');return}
 if(current==='locked'){show(resumeScreen);return}
 if(current==='privacy'&&(e.label==='Back'||e.label==='Keep this session')){show(privacyOrigin);return}
 if(current==='dashboard'&&e.to==='phone'&&paired){show('connected');return}
 show(e.to)
 };box.append(button)}$('#screen-status').textContent=s.title.replaceAll('\n',' ')+' · '+(id==='locked'?'setup paused':'parked demo');$('#park').textContent=id==='locked'?'Return to Park and resume':'Preview outside-Park state';document.querySelectorAll('[data-screen]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.screen===id)));if(focused&&manual)box.querySelector('button')?.focus({preventScroll:true})}
fetch('screens.json').then(r=>{if(!r.ok)throw Error('Screens unavailable');return r.json()}).then(data=>{screens=data;show('dashboard')}).catch(()=>{$('#hmi').innerHTML='<p style="padding:30px">The interactive preview could not load. Please refresh the page.</p>'});
document.querySelectorAll('[data-screen]').forEach(b=>b.onclick=()=>show(b.dataset.screen));document.querySelectorAll('[data-jump]').forEach(b=>b.onclick=()=>{show(b.dataset.jump);$('#experience').scrollIntoView({behavior:reduced.matches?'instant':'smooth'})});$('#restart').onclick=()=>{paired=false;temperature=21;show('dashboard')};$('#park').onclick=()=>show(current==='locked'?resumeScreen:'locked');$('#play').onclick=()=>{if(timer){stop();return}if(!screens.length)return;walkIndex=0;paired=false;temperature=21;show(walk[0],false);$('#play').textContent='Pause walkthrough Ⅱ';$('#play').setAttribute('aria-pressed','true');timer=setInterval(()=>{walkIndex++;if(walkIndex>=walk.length){stop();return}show(walk[walkIndex],false)},4500)};document.addEventListener('visibilitychange',()=>{if(document.hidden)stop()});new IntersectionObserver(entries=>{if(!entries[0].isIntersecting)stop()},{threshold:.1}).observe($('#experience'));
const phones=[['01-discover','Meet your rental.','A concise introduction to the car and the three things worth exploring before collection.'],['02-prepare','Choose your focus.','Comfort, essential controls and optional audio pairing are grouped into three approachable starting points.'],['03-guide','Recognise the essentials.','The control guide pairs a location with a plain-language instruction, ready to revisit in the parked car.'],['04-ready','Continue in the car.','The preview ends with a clear handover to the parked setup. Physical adjustments happen in the vehicle.']];function phone(i){phoneIndex=i;const p=phones[i];$('#phone-image').src=`companion/${p[0]}.svg`;$('#phone-image').alt='SETGO companion app: '+p[1];$('#phone-title').textContent=p[1];$('#phone-caption').textContent=p[2];document.querySelectorAll('[data-phone]').forEach(b=>b.setAttribute('aria-pressed',String(Number(b.dataset.phone)===i)));$('#phone-next').textContent=i===3?'Back to introduction ↺':'Next screen →'}document.querySelectorAll('[data-phone]').forEach(b=>b.onclick=()=>phone(Number(b.dataset.phone)));$('#phone-next').onclick=()=>phone((phoneIndex+1)%phones.length);

const large=$('#large-preview'),homeHost=$('.cockpit'),hmi=$('#hmi');$('#expand').onclick=()=>{stop();$('#large-mount').append(hmi);large.showModal();document.body.style.overflow='hidden'};$('#close-large').onclick=()=>large.close();large.addEventListener('close',()=>{homeHost.insertBefore(hmi,homeHost.querySelector('.vent'));document.body.style.overflow='';$('#expand').focus({preventScroll:true})});
