'use strict';
const $=s=>document.querySelector(s);
let screen='prepare',scenario='normal',departureTime='23:25';
document.addEventListener('change',e=>{if(e.target.id==='departureTime'&&e.target.value)departureTime=e.target.value});
function phone(){
 $('#phoneTime').textContent=scenario==='late'?'23:40':'23:25';
 let title='Plan your departure.',body='What time do you expect to leave work today? Think about remaining closing tasks, rather than your scheduled shift end.',extra='<label for="departureTime">When do you expect to leave today, including closing tasks?</label><input id="departureTime" type="time" value="'+departureTime+'" style="display:block;width:100%;padding:12px;margin:10px 0 18px;font:inherit;border:1px solid #aaa;border-radius:12px">',buttons='<button class="phone-btn" data-next="pause">Review my journey (optional) ↗</button><button class="phone-btn alt" data-next="sorted">My journey is already arranged</button><button class="phone-btn alt" data-next="help">I need help with a closing task</button>';
 if(screen==='help'){title='Ask the closing supervisor.';body='Proposed recipient: the closing supervisor on duty. Raise the remaining task and expected departure together. The supervisor can review task allocation or contact the transport coordinator.';extra='<div class="phone-card"><strong>Draft · not sent</strong><p>In a live service, the assigned supervisor’s name would appear here. No supervisor is assigned in this prototype.</p></div>';buttons='<button class="phone-btn" data-next="pending">Preview a pending request</button><button class="phone-btn alt" data-next="prepare">Back to departure</button>'}
 else if(screen==='pending'){title='Awaiting a response.';body='Example state: the request is addressed to the closing supervisor, but no response is recorded. A pending request does not mean task cover or transport is arranged.';extra='<p class="small">If time is tight, speak directly to the supervisor. No notification has been sent in this demo.</p>';buttons='<button class="phone-btn" data-next="responded">Preview an action response</button><button class="phone-btn alt" data-next="unavailable">Preview support unavailable</button>'}
 else if(screen==='responded'){title='Response with a next step.';body='Example supervisor response: “I will review who can help with cleaning and ask the transport coordinator about the pickup.”';extra='<div class="phone-card"><strong>Still to confirm</strong><p>Who will cover the task, whether pickup can change, and who pays for any alternative. A response is not a confirmed ride.</p></div>';buttons='<button class="phone-btn" data-next="prepare">Review expected departure</button>'}
 else if(screen==='unavailable'){title='Support is not confirmed.';body='Example supervisor response: “Task cover is not available yet. Speak with me to review the remaining work.” Transport changes and payment are unresolved.';extra='<p class="small">This state makes the limit visible rather than promising a ride or permission to leave.</p>';buttons='<button class="phone-btn" data-next="continue">Review transport options</button><button class="phone-btn alt" data-next="prepare">Back to departure</button>'}
 else if(screen==='personal'){title='Check your shared plan.';body='A personal or colleague lift counts as an existing arrangement. Agree the departure and meeting point directly with the person giving the lift.';extra='<p class="small">This check does not notify your driver or book transport.</p>';buttons='<button class="phone-btn" data-next="done">My arrangement is confirmed</button><button class="phone-btn alt" data-next="continue">It is not confirmed</button>'}
 else if(screen==='sorted'){title='Keep what works.';body='If your journey is already arranged, you can finish this check without reviewing alternatives.';extra='';buttons='<button class="phone-btn" data-next="pickup">I have an employer pickup</button><button class="phone-btn alt" data-next="personal">Personal or colleague lift</button>'}
 else if(screen==='pickup'){title='Confirm with your provider.';body='Check the pickup time and meeting point with your employer or transport contact. This check does not notify your driver or book transport. Confirm changes directly with the employer’s transport coordinator.';extra='';buttons='<button class="phone-btn" data-next="done">I’ve checked my pickup</button><button class="phone-btn alt" data-next="continue">Pickup is not confirmed</button>'}
 else if(screen==='done'){title='Your check is complete.';body='You have marked your arrangement as sorted in this demonstration. This check does not notify your driver, book or pay for transport. Recheck your plan if your departure time changes.';extra='';buttons='<button class="phone-btn" data-next="reset">Restart demo</button>'}
 else if(scenario==='offline'){title='A conversation still works.';body='Use the paper departure prompt and speak with the shift lead about unfinished tasks and available information. No live departure can be confirmed here.';extra='';buttons='<button class="phone-btn" data-next="help">Review the task-support prompt</button><button class="phone-btn alt" data-next="reset">Restart demo</button>'}
 else if(screen==='continue'){title='An option, not a booking.';body='Review the next service, another route or a directly agreed lift. Availability and prices must be checked with the provider or colleague.';extra='<div class="phone-card"><strong>Option only — not booked</strong><p>Price unavailable here. Confirm the fare before choosing. No payment or reservation is made.</p></div>';buttons='<button class="phone-btn" data-next="help">Review closing-task support</button><button class="phone-btn alt" data-next="prepare">Back to departure</button>'}
 else if(scenario==='closed'){title='Timing may not work.';body='In this example, leaving later may mean missing a connection. This is a timing concern, not a service cancellation. Check the actual departure with your local information source.';extra='<p class="small">Illustrative scenario; no timetable or connection-risk calculation is connected.</p>';buttons='<button class="phone-btn" data-next="continue">Review options ↗</button><button class="phone-btn alt" data-next="help">I need help with a closing task</button>'}
 else if(screen==='pause'){title='Check both legs.';body='Your expected departure is '+departureTime+'. Check the first service and any onward connection through your usual local information source. A later departure may affect the connection; this prototype cannot calculate whether you will catch it.';extra='';buttons='<button class="phone-btn" data-next="continue">Review fallback options ↗</button><button class="phone-btn alt" data-next="sorted">My journey is already arranged</button>'}
 else if(scenario==='late'){title='Closing ran late.';body='Update when you expect to leave, then check the journey again. If unfinished tasks are delaying departure, ask the closing supervisor to review the work.'}
 $('#phoneContent').innerHTML=`<p class="mini-title">WORKPLACE DEPARTURE CHECK</p><h3>${title}</h3><div class="phone-card"><p>${body}</p></div>${extra}${buttons}<p class="phone-footer">Concept demonstration. No live departures, confirmed lifts or messages.</p>`;
 document.querySelectorAll('[data-screen]').forEach(x=>x.setAttribute('aria-pressed',String(x.dataset.screen===screen)));
}
document.addEventListener('click',e=>{const next=e.target.closest('[data-next]');if(next){screen=next.dataset.next;if(screen==='reset'){screen='prepare';scenario='normal';$('#scenario').value='normal'}phone()}const tab=e.target.closest('[data-screen]');if(tab){screen=tab.dataset.screen;phone()}const r=e.target.closest('[data-role]');if(r)renderRole(r.dataset.role)});
$('#scenario').addEventListener('change',e=>{scenario=e.target.value;screen='prepare';phone()});
$('#shiftTime').addEventListener('input',e=>{const v=+e.target.value;$('#shiftLabel').value='23:'+String(v-1380).padStart(2,'0');$('#timeReadout').textContent=(v-1380)+' minutes after the scheduled 23:00 shift end.'});
const roles={
worker:{name:'Workers',give:'Their readiness check, travel choices and optional feedback.',receive:'A clear moment to review the journey and raise closing delays.',boundary:'No obligation to disclose a home address or accept a shared lift.'},
employer:{name:'Employer / shift lead',give:'Task allocation, paid time for the check and a response to closing overruns.',receive:'Visibility of closing-process friction and an opportunity to address it.',boundary:'Cannot treat the service as permission for routine overtime or claim unmeasured retention gains.'},
host:{name:'Colleagues',give:'An optional conversation about a shared journey when finishing times align.',receive:'The same freedom to accept or decline coordination.',boundary:'No assumed availability, compulsory lifts or guaranteed transport.'},
coordinator:{name:'Service owner',give:'Departure prompts, local information references and review of recurring problems.',receive:'Aggregate feedback on whether the process is useful.',boundary:'A proposed workplace role; no partner or operator has committed to delivery.'},
public:{name:'Transport information',give:'Locally available timetable or departure information where accessible.',receive:'No formal value exchange or integration is assumed.',boundary:'Noida is the location; specific providers and routes are not established. No API or live data is connected.'}
};
function renderRole(id){const r=roles[id];document.querySelectorAll('[data-role]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.role===id)));$('#ecoDetail').innerHTML=`<span class="eyebrow">PROPOSED VALUE EXCHANGE</span><h3 style="margin-top:22px">${r.name}</h3><dl><dt>Contributes</dt><dd>${r.give}</dd><dt>Receives</dt><dd>${r.receive}</dd><dt>Boundary</dt><dd>${r.boundary}</dd></dl>`}
function progress(){const h=document.documentElement.scrollHeight-innerHeight;$('.progress').style.width=(h?scrollY/h*100:0)+'%'}window.addEventListener('scroll',progress,{passive:true});
if('IntersectionObserver' in window){document.body.classList.add('js-ready');const observer=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('in');observer.unobserve(e.target)}}),{threshold:.05});document.querySelectorAll('.reveal').forEach(e=>observer.observe(e))}

phone();renderRole('worker');progress();
const sources=[{"id": "P1", "title": "Restaurant worker \u00b7 exploratory conversation", "geography": "Noida, Delhi NCR, India", "period": "Interview date not recorded", "finding": "Scheduled finish 23:00; cleaning often extends departure to 23:25\u201323:40. Bus followed by approximately 15 minutes walking. Missing the bus means a long wait. A colleague\u2019s lift helps when shifts align.", "limitation": "One participant\u2019s account, supplied as a paraphrased summary. No bus timetable or exact waiting duration was supplied."}, {"id": "P2", "title": "Retail worker \u00b7 exploratory conversation", "geography": "Noida, Delhi NCR, India", "period": "Interview date not recorded", "finding": "Usually leaves around 22:15 after till closing. Approximately 45-minute journey with one change. Late closing can cause a missed connection. Checking live departures helps.", "limitation": "One participant\u2019s account, supplied as a paraphrased summary. Scheduled finish time and delay duration were not supplied."}];
$("#sourceList").innerHTML=sources.map(s=>`<details id="source-${s.id}"><summary>${s.id} / ${s.title}</summary><p><strong>${s.geography} · ${s.period}</strong></p><p>${s.finding}</p><p>${s.limitation}</p></details>`).join("");
